"""empty message

Revision ID: 316e595f69cb
Revises: 
Create Date: 2020-07-11 12:34:07.467341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316e595f69cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('dates',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dateId', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('dateId')
    )
    op.create_table('location_information',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('inform', sa.PickleType(), nullable=True),
    sa.Column('placeId', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('play_list',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('startTime', sa.PickleType(), nullable=True),
    sa.Column('index', sa.PickleType(), nullable=True),
    sa.Column('tranList', sa.PickleType(), nullable=True),
    sa.Column('cost', sa.PickleType(), nullable=True),
    sa.Column('tranTime', sa.PickleType(), nullable=True),
    sa.Column('note', sa.PickleType(), nullable=True),
    sa.Column('stayTime', sa.PickleType(), nullable=True),
    sa.Column('indexPlaceName', sa.PickleType(), nullable=True),
    sa.Column('costTran', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['date'], ['dates.dateId'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('play_list')
    op.drop_table('location_information')
    op.drop_table('dates')
    op.drop_table('users')
    # ### end Alembic commands ###
